version: "3.9"

volumes:
  gz_config:
  jupyter_config:
  rviz2_config:
  workdir:

services:
  aim-nxp-2025:
    ports:
      - 127.0.0.1:8888:8888
      - 127.0.0.1:8000:8000
    environment:
      - HOST_UID=${HOST_UID}
      - HOST_GID=${HOST_GID}
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - RUN_VNC=false
      - RUN_ZETH=true
      - MESA_GL_VERSION_OVERRIDE=4.5
      - MESA_GLSL_VERSION_OVERRIDE=450
      - __GL_SYNC_TO_VBLANK=0 # May reduce tearing but can help with performance
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    image: git.thecount.eu.org/thecountrox/aim-nxp-2025:1.0
    build:
      dockerfile: Dockerfile
    tty: true
    ipc: host
    stdin_open: true
    privileged: true # Privileged can solve many issues but is less secure. Try to solve without it if possible.
    hostname: dream
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - ./work:/home/user/cognipilot/workspace
      - gz_config:/home/user/.gz
      - jupyter_config:/home/user/.jupyter
      - rviz2_config:/home/user/.rviz2
      - workdir:/home/user/cognipilot
      - /tmp/.X11-unix:/tmp/.X11-unix:rw # Essential for X11
      - $HOME/.gnupg:/home/user/.gnupg
      - $HOME/.ssh:/home/user/.ssh
      - $HOME/.gitconfig:/home/user/.gitconfig
      # IMPORTANT: If you are NOT using `deploy: resources:` (e.g., for AMD/Intel or older Docker)
      # You need to explicitly mount the DRI device:
      - /dev/dri:/dev/dri:rw # Provides access to GPU for direct rendering

    # Recommended for NVIDIA GPUs with nvidia-container-toolkit installed on host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # Or a specific number, e.g., '1'
              capabilities: [gpu, graphics, compute] # Be explicit about capabilities
